#!/usr/bin/env ruby

def run_git_whistespace_check()
  puts "Checking for whitespace errors..."
  git_ws_check = `git diff-index --color-words --check --cached HEAD --`
  unless $?.success?
    puts git_ws_check
    exit 1
  end
end

def run_tailor(files)
  puts 'Checking syntax...'
  files.lines do |file|
    file.chomp! # remove carriage returns
    tailor_output = `tailor --max-line-length 999 #{ file }`
    unless $?.success?
      puts tailor_output
      exit 1
    end
  end
  puts "\tcleared #{ STAGED_FILES.lines.count } files"
end

PARENT_PATH = "#{ `git rev-parse --show-toplevel`.chomp }"
COOKBOOK_PATH = "#{ PARENT_PATH}/cookbooks/" 

def run_knife_test(path, dirs)
  puts "Checking for cookbook errors..."
  dirs.lines do |dir|
  dir.chomp!
    knife_output = `knife cookbook test #{ dir } -c #{ path }/.chef/knife.rb`
    unless $?.success?
      puts knife_output
      exit 1
    end
  end
  puts "\tknife cookbook test #{ STAGED_COOKBOOKS.gsub("\n", ', ') }"
end


def run_foodcritic(dirs, rules)
  puts "Running foodcritic..."
  dir.lines do |dir|
    dir.chomp!
    fc_output = `foodcritic --tags #{ rules } cookbooks/#{ dir }`
      unless $?.success?
      puts fc_output
      exit 1
    end
  end
  puts "\tfoodcritiqued #{ STAGED_COOKBOOKS.gsub("\n", ', ') } cookbooks"
end

run_git_whitespace_check()

# Get the file names of (A)dded, (C)opied, (M)odified Ruby files 
STAGED_FILES = `git diff-index --name-only --diff-filter=ACM HEAD -- '*.rb'`
run_tailor(STAGED_FILES)

STAGED_COOKBOOKS = `git diff-index --name-only --diff-filter=ACM HEAD -- '*.rb' | cut -d/ -f2 | sort | uniq`
run_knife_test(PARENT_PATH, dir)

rules = "FC006,FC008,FC009,FC010,FC018,FC030,FC031,FC032,FC037,FC038,FC040,FC042"
run_foodcritic(STAGED_COOKBOOKS, rules)

